In [1]:
from sklearn.metrics import confusion_matrix
import numpy as np

In [2]:
preds = open('preds.txt').read()[1:-1].split(', ')
true_labels = open('true_labels.txt').read()[1:-1].split(', ')
labels = ['Airplane', 'Automobile', 'Bird', 'Cat', 'Deer', 'Dog', 'Frog', 'Horse', 'Ship', 'Truck']

In [3]:
conf_matrix = confusion_matrix(true_labels, preds)
acc = np.round(np.count_nonzero(np.array(true_labels) == np.array(preds)) / len(preds), 2)

print(f'Accuracy: {acc}')
print(f'Confusion matrix:\n{conf_matrix}')
print('\nClasses:\n\t' + '\n\t'.join(labels))

Accuracy: 0.5
Confusion matrix:
[[ 934   70   92   52   76   43   46   51  204   88]
 [  68 1022   41   54   36   21   55   38  109  210]
 [ 166   33  676  131  256   81  209   76   41   29]
 [  52   47  186  554  120  270  230   63   53   58]
 [  93   27  215   98  724   86  242  129   41   25]
 [  42   43  176  339  112  595  148   89   28   34]
 [  25   26  135  163  154   92  938   30   15   32]
 [  83   37  143  105  183   85   62  849   34   65]
 [ 193   95   44   43   48   36   17   18 1079   92]
 [  92  262   47   62   34   53   52   58  100  892]]

Classes:
	Airplane
	Automobile
	Bird
	Cat
	Deer
	Dog
	Frog
	Horse
	Ship
	Truck


In [8]:
for s, l in np.c_[np.diag(conf_matrix) / np.sum(conf_matrix, axis=1), labels]:
    print(f'{l}: {np.round(float(s), 2)}')

Airplane: 0.56
Automobile: 0.62
Bird: 0.4
Cat: 0.34
Deer: 0.43
Dog: 0.37
Frog: 0.58
Horse: 0.52
Ship: 0.65
Truck: 0.54
